name: BUILD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
     # virtual environments: https://github.com/actions/virtual-environments
      runs-on: macos-12

      steps:
       - name: Checkout
         uses: actions/checkout@v2
        
       - name: Test the code (unit tests)
         run: bazel test //tests/...

       - name: Upload coverage reports to Codecov
         uses: codecov/codecov-action@v3
