name: BUILD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    test:
     # virtual environments: https://github.com/actions/virtual-environments
      runs-on: macos-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Test the code (unit tests)
        run: bazel test //tests:DoubleVector

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
